# Site settings
title: Seungwon
email: tmddnjsrla99@gmail.com
description: >-
  개발 블로그
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://ori0o0p.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ori0o0p

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"

# Collections
collections:
  category:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "category"
    values:
      layout: "category"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
